#!/bin/bash
echo '#include "defs.h"' > struct264.c
echo '#include "operators.h"' >> struct264.c

python -m tools.move_func sub_4871C0 struct264.c
python -m tools.update sub_4871C0 -1 'struct264*'
python -m tools.move_func sub_487150 struct264.c
python -m tools.update sub_487150 -1 'struct264*'
python -m tools.move_func sub_487310 struct264.c
python -m tools.update sub_487310 0 'struct264*'
python -m tools.move_func sub_431270 struct264.c
python -m tools.move_func sub_487680 struct264.c
python -m tools.update sub_487680 0 'struct264*'
python -m tools.move_func sub_431290 struct264.c
python -m tools.move_func sub_487970 struct264.c
python -m tools.update sub_487970 0 'struct264*'
python -m tools.move_func sub_487590 struct264.c
python -m tools.update sub_487590 0 'struct264*'
python -m tools.move_func sub_4872C0 struct264.c
python -m tools.update sub_4872C0 0 'struct264*'
python -m tools.move_func sub_4876A0 struct264.c
python -m tools.update sub_4876A0 0 'struct264*'
python -m tools.move_func sub_487910 struct264.c
python -m tools.update sub_487910 0 'struct264*'
python -m tools.move_func sub_452810 struct264.c
python -m tools.move_func sub_487810 struct264.c
python -m tools.update sub_487810 0 'struct264*'
python -m tools.move_func sub_4877D0 struct264.c
python -m tools.update sub_4877D0 0 'struct264*'
# Need function pointer for this one
python -m tools.move_func sub_4873C0 struct264.c
python -m tools.move_func sub_4BDA60 struct264.c
python -m tools.move_func sub_4BDA80 struct264.c
python -m tools.move_func sub_4877F0 struct264.c
python -m tools.move_func sub_487360 struct264.c

python -m tools.fix_compile struct264.c
# python -m tools.alias_repeat
