#!/bin/bash
echo '#include "defs.h"' > struct264.c
echo '#include "operators.h"' >> struct264.c
echo '' >> struct264.c
echo 'void* dword_5d4594_805984 = 0;' >> struct264.c

patch -u << EOF
diff --git a/src/legacy/GAME1_2.c b/src/legacy/GAME1_2.c
index 35c741b1b..3896e229a 100644
--- a/src/legacy/GAME1_2.c
+++ b/src/legacy/GAME1_2.c
@@ -129,8 +129,6 @@ nox_screenParticle* dword_5d4594_806052 = 0;

 void* dword_5d4594_814624 = 0;

-void* dword_5d4594_805984 = 0;
-
 //----- (00427F30) --------------------------------------------------------
 int nox_xxx_wallMath_427F30(int2* a1, int* a2) {
        int v2;  // esi
EOF

python -m tools.move_func sub_4871C0 struct264.c
python -m tools.update sub_4871C0 -1 'struct264*'
python -m tools.move_func sub_487150 struct264.c
python -m tools.update sub_487150 -1 'struct264*'
python -m tools.move_func sub_487310 struct264.c
python -m tools.update sub_487310 0 'struct264*'
python -m tools.move_func sub_431270 struct264.c
python -m tools.move_func sub_487680 struct264.c
python -m tools.update sub_487680 0 'struct264*'
python -m tools.move_func sub_431290 struct264.c
python -m tools.move_func sub_487970 struct264.c
python -m tools.update sub_487970 0 'struct264*'
python -m tools.move_func sub_487590 struct264.c
python -m tools.update sub_487590 0 'struct264*'
python -m tools.move_func sub_4872C0 struct264.c
python -m tools.update sub_4872C0 0 'struct264*'

# python -m tools.update sub_451920 0 'struct200*'
# python -m tools.update sub_451BE0 0 'struct576*'
# python -m tools.update sub_451CA0 0 'struct576*'
# python -m tools.update sub_451F30 0 'struct576*'
# python -m tools.update sub_451F90 0 'struct576*'
# python -m tools.update sub_451FE0 0 'struct576*'
# python -m tools.update sub_452050 0 'struct576*'
# python -m tools.update sub_452120 0 'struct576*'
# python -m tools.update sub_452190 0 'struct200*'
# python -m tools.update nox_xxx_draw_452300 0 'struct200*'
# python -m tools.update sub_4523D0 0 'struct576*'
# python -m tools.update sub_452410 0 'struct576*'
# python -m tools.update sub_452490 0 'struct576*'
# python -m tools.update sub_452510 0 'struct576*'
# python -m tools.update sub_452690 0 'struct576*'
# python -m tools.update sub_452E90 1 'struct576*'
# python -m tools.update sub_452EE0 0 'struct576*'
# python -m tools.update sub_452F10 0 'struct576*'
# python -m tools.update sub_452F50 0 'struct576*'
# python -m tools.update sub_452F80 0 'struct576*'
# python -m tools.update sub_452FE0 0 'struct576*'
# python -m tools.update sub_452580 0 'struct576*'
# python -m tools.compile_audio
# python -m tools.alias_repeat
