#!/bin/bash
echo '#include "defs.h"' > struct88.c
echo '#include "operators.h"' >> struct88.c

python -m tools.move_func sub_486FE0 struct88.c
python -m tools.update sub_486FE0 -1 'struct88*'
python -m tools.move_func sub_487030 struct88.c
python -m tools.update sub_487030 0 'struct88*'
python -m tools.move_func sub_487050 struct88.c
python -m tools.update sub_487050 0 'struct88*'
python -m tools.move_func sub_4870A0 struct88.c
python -m tools.move_func sub_4870E0 struct88.c
python -m tools.move_func sub_487070 struct88.c
python -m tools.move_func sub_487090 struct88.c
python -m tools.move_func sub_487100 struct88.c
python -m tools.move_func sub_4875B0 struct88.c
python -m tools.move_func sub_4875D0 struct88.c
python -m tools.move_func sub_4875F0 struct88.c

# python -m tools.update sub_4871C0 -1 'struct264*'
# python -m tools.move_func sub_487150 struct264.c
# python -m tools.update sub_487150 -1 'struct264*'
# python -m tools.move_func sub_487310 struct264.c
# python -m tools.update sub_487310 0 'struct264*'
# python -m tools.move_func sub_431270 struct264.c
# python -m tools.move_func sub_487680 struct264.c
# python -m tools.update sub_487680 0 'struct264*'
# python -m tools.move_func sub_431290 struct264.c
# python -m tools.move_func sub_487970 struct264.c
# python -m tools.update sub_487970 0 'struct264*'
# python -m tools.move_func sub_487590 struct264.c
# python -m tools.update sub_487590 0 'struct264*'
# python -m tools.move_func sub_4872C0 struct264.c
# python -m tools.update sub_4872C0 0 'struct264*'
# python -m tools.move_func sub_4876A0 struct264.c
# python -m tools.update sub_4876A0 0 'struct264*'
# python -m tools.move_func sub_487910 struct264.c
# python -m tools.update sub_487910 0 'struct264*'
# python -m tools.move_func sub_452810 struct264.c
# python -m tools.move_func sub_487810 struct264.c
# python -m tools.update sub_487810 0 'struct264*'
# python -m tools.move_func sub_4877D0 struct264.c
# python -m tools.update sub_4877D0 0 'struct264*'
# # Need function pointer for this one
# # python -m tools.move_func sub_4873C0 struct264.c
# python -m tools.move_func sub_4877F0 struct264.c
# python -m tools.move_func sub_487360 struct264.c

python -m tools.fix_compile struct88.c
# python -m tools.alias_repeat
#
python -m tools.create_imports struct88.c

python -m tools.translate_c_to_go struct88.c

# Replace module inside calls to prefix `m.`
# go run ./gotools struct312/struct312_impl.go

# Find all function pointer invocations. They should use ccall instead.
go run ./tools/funcptr_analyzer struct88/struct88_impl.go
