#!/bin/bash
echo '#include "defs.h"' > phase6.c
echo '#include "operators.h"' >> phase6.c

python -m tools.move_func sub_4BDA80 phase6.c
python -m tools.update sub_4BDA80 0 'struct312*'
python -m tools.move_func sub_486E90 phase6.c
python -m tools.update sub_486E90 0 'struct312*'
python -m tools.move_func sub_4BDA60 phase6.c
python -m tools.update sub_4BDA60 0 'struct312*'
python -m tools.move_func sub_4873C0 phase6.c

python -m tools.fix_compile phase6.c

python -m tools.create_imports phase6.c

python -m tools.translate_c_to_go phase6.c

# Replace module inside calls to prefix `m.`
# go run ./gotools struct312/struct312_impl.go

# Find all function pointer invocations. They should use ccall instead.
go run ./tools/funcptr_analyzer audio/phase6_impl.go
