#!/bin/bash
echo '#include <stdio.h>' > phase7.c
echo '' >> phase7.c
echo '#include "defs.h"' >> phase7.c
echo '#include "operators.h"' >> phase7.c
echo '#include "common/fs/nox_fs.h"' >> phase7.c

FUNC_NAME=sub_4BD470

# python -m tools.add_cgo_decl $FUNC_NAME &

# python -m tools.move_func sub_4BD680 phase7.c
# python -m tools.move_func sub_487C50 phase7.c
# python -m tools.move_func sub_4BD690 phase7.c
# python -m tools.move_func sub_4BD600 phase7.c
# python -m tools.move_func sub_425900 phase7.c
# python -m tools.move_func sub_487D30 phase7.c
# python -m tools.move_func sub_4BD280 phase7.c
# python -m tools.move_func sub_4BD2E0 phase7.c
# python -m tools.move_func sub_4BD2D0 phase7.c
# python -m tools.move_func sub_4BD3C0 phase7.c
# python -m tools.move_func sub_4866D0 phase7.c
# python -m tools.move_func sub_487C30 phase7.c
# python -m tools.move_func sub_487D00 phase7.c
# python -m tools.move_func sub_4BD340 phase7.c
# python -m tools.move_func sub_4BD3C0 phase7.c
# python -m tools.move_func sub_486AA0 phase7.c
# python -m tools.move_func sub_4BD420 phase7.c

# python -m tools.move_func $FUNC_NAME phase7.c
python -m tools.move_func sub_486DB0 phase7.c
python -m tools.move_func sub_486E00 phase7.c
python -m tools.move_func sub_486B60 phase7.c

python -m tools.fix_compile phase7.c

# python -m tools.create_imports phase7.c

python -m tools.translate_c_to_go2 phase7.c

# Replace module inside calls to prefix `m.`
# go run ./gotools audio/phase7_impl.go

# Find all function pointer invocations. They should use ccall instead.
go run ./tools/funcptr_analyzer audio/audio_impl.go

rm phase7.c
