#!/usr/bin/env bash
set -euo pipefail

export GOARCH=386
export CGO_ENABLED=1
export CGO_CFLAGS_ALLOW='(-fshort-wchar)|(-fno-strict-aliasing)|(-fno-strict-overflow)'
export CGO_CFLAGS="-fprofile-arcs -ftest-coverage ${CGO_CFLAGS:-}"
export CGO_LDFLAGS="--coverage ${CGO_LDFLAGS:-}"

go test -count=1 -tags ccover ./...
